name: Build and Release Snap

on:
  push:
    branches:
      - 'master'
    tags:
      - '*.*.*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        architecture:
        - amd64
        - i386
        - armhf
        - arm64
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    -
      name: Docker meta
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: BIBOLV/wmbusmeters
        tags: type=ref,event=tag
    - name: Build
      id: build
      uses: diddlesnaps/snapcraft-multiarch-action@v1
      with:
        architecture: ${{ matrix.architecture }}
    - name: Publish release to Stable
      uses: snapcore/action-publish@v1
      if: ${{ steps.meta.outputs.tags }}
      with:
        store_login: ${{ secrets.STORE_LOGIN }}
        snap: ${{ steps.build.outputs.snap }}
        release: stable
    - name: Publish latest to Edge
      uses: snapcore/action-publish@v1
      if: ${{ !steps.meta.outputs.tags }}
      with:
        store_login: ${{ secrets.STORE_LOGIN }}
        snap: ${{ steps.build.outputs.snap }}
        release: edge
