name: Build docker image

on:
  push:
    branches:
      - 'master'
    tags:
      - '*.*.*'

jobs:
  multiarch_docker_build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64, arm64, armhf]
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: BIBOLV/wmbusmeters
          tags: type=ref,event=tag
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASS }}
      -
        name: Build and push not tagged release
        if: ${{ !steps.meta.outputs.tags }}
        uses: docker/build-push-action@v3
        with:
          context: docker/
          platforms: linux/${{ matrix.arch }}
          push: true
          build-args: arch=${{ matrix.arch }}
          tags: bibolv/wmbusmeters:latest
      -
        name: Build and push tagged release
        if: ${{ steps.meta.outputs.tags }}
        uses: docker/build-push-action@v3
        with:
          context: docker/
          platforms: ${{ matrix.arch }}
          push: true
          build-args: arch=${{ matrix.arch }}
          tags: bibolv/wmbusmeters:release-${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.version'] }}
