name: Build HA add-on

on:
  push:
    branches:
      - ha-docker

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - run: git fetch --prune --unshallow

      - name: Get version
        id: version
        run: |
          if [ -n "$(git describe --tags | grep -)" ]; then
            GIT_VER="$(git describe --tags | cut -f1,2 -d'-')"
            echo "id=${GIT_VER}" >> $GITHUB_OUTPUT
          else
            GIT_VER="$(git describe --tags)"
            echo "id=${GIT_VER}" >> $GITHUB_OUTPUT
          fi

      - name: Update README and set version in config.json
        run: |
          sed -i "s/\s\{4,\}\"version\".*/    \"version\": \"${{ steps.version.outputs.id }}\"\,/g" ha-addon/config.json
          cat ha-addon/config.json

      - uses: actions/upload-artifact@v3
        with:
          name: ha-addon_artifact-${{ steps.version.outputs.id }}
          path: ${{ github.workspace }}
          retention-days: 1

    outputs:
      id: ${{ steps.version.outputs.id }}

  build:
    needs: prepare
    runs-on: ubuntu-latest
    name: Build ${{ matrix.arch }} ${{ matrix.addon }} add-on
    strategy:
      matrix:
        addon: ["wmbusmeters"]
        arch: ["armv7", "aarch64", "amd64"]
    steps: 
      - uses: actions/download-artifact@v3
        with:
          name: ha-addon_artifact-${{ needs.prepare.outputs.id }}

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASS }}

      - name: Build ${{ matrix.addon }} ${{ matrix.arch }} HA add-on
        uses: home-assistant/builder@master
        with:
          args: |
            --${{ matrix.arch }} \
            --target /data/ha-addon \
            --version ${{ needs.prepare.outputs.id }}

  update-repo:
    needs: [prepare, build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: ha-addon_artifact-${{ needs.prepare.outputs.id }}

      - name: Push changed files back to repo
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add -A
          git commit -m "Auto Push - update ha-addon config and readme - [no ci]"
          git push
