name: Build HA add-on

on:
  push:
    branches:
      - ha-docker

jobs:
  prepare:
    steps:
      - name: Check out repository
        uses: actions/checkout@v2.4.0
      - run: git fetch --prune --unshallow

      - name: Login to DockerHub
        uses: docker/login-action@v1.12.0
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASS }}

      - name: Get version
        id: version
        run: |
          if [ -n "$(git describe --tags | grep -)" ]; then
            GIT_VER="$(git describe --tags | cut -f1,2 -d'-')"
            echo "::set-output name=id::$(echo "$GIT_VER")"
          else
            GIT_VER="$(git describe --tags)"
            echo "::set-output name=id::$(echo "$GIT_VER")"
          fi

      - name: Update README and set version in config.json
        run: |
          sed -i "s/    \"version\".*/    \"version\": \"$steps.version.outputs.id\"\,/g" ha-addon/config.json
          cat README.md

  build:
    runs-on: ubuntu-latest
    name: Build ${{ matrix.arch }} ${{ matrix.addon }} add-on
    strategy:
      matrix:
        addon: ["wmbusmeters"]
        arch: ["armv7", "aarch64", "amd64"]

      - name: Build ${{ matrix.addon }} ${{ matrix.arch }} HA add-on
        uses: home-assistant/builder@master
        with:
          args: |
            --${{ matrix.arch }} \
            --target /data/ha-addon \
            --version ${{ steps.version.outputs.id }}

      - name: Push changed files back to repo
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add -A
          git commit -m "Auto Push - update ha-addon config and readme - [no ci]"
          git push
