name: Trigger HA add-on build

on:
  push:
    branches:
      - master

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - id: get_version
        uses: battila7/get-version-action@v2
      - run: echo ${{ steps.get_version.outputs.version }}
      - run: echo ${{ steps.get_version.outputs.version-without-v }}
      - run: echo ${{ steps.get_version.outputs.patch }}
      - run: echo ${{ steps.get_version.outputs.prerelease }}
      - run: echo ${{ steps.get_version.outputs.build }}

      - name: Trigger build for edge release
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.HA_PAT }}
          repository: BIBOLV/wmbusmeters-ha-addon
          event-type: build_ha_edge
          client-payload: '{"github": ${{ toJson(github) }}}'