name: Trigger HA add-on build

on:
  push:
    branches:
      - master
    tags:
      - '*.*.*'

jobs:
  trigger_ha_build:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.event.release.tag_name }}