name: Trigger HA add-on build

on:
  push:
    branches:
      - master
    tags:
      - '*.*.*'

jobs:
  trigger_ha_build:
    runs-on: ubuntu-latest
    steps:
     - name: GitHub Tag Name example
       run: |
         echo "Tag name from GITHUB_REF_NAME: $GITHUB_REF_NAME"
         echo "Tag name from github.ref_name: ${{  github.ref_name }}"