name: Trigger HA add-on build

on:
  push:
    branches:
      - master

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2.4.0
      - run: git fetch --prune --unshallow

      - name: Get version
        id: version
        run: |
          if [ -n "$(git describe --tags | grep -)" ]; then
            GIT_VER="$(git describe --tags | cut -f1,2 -d'-')"
            echo "::set-output name=id::$(echo "$GIT_VER")"
          else
            GIT_VER="$(git describe --tags)"
            echo "::set-output name=id::$(echo "$GIT_VER")"
          fi

      - run: echo "${{ steps.version.outputs.id }}"

      - run: echo "${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.version'] }}"
